theme: osuny
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false
  seo:
    title:
      separator: "•"
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-blanc.svg"